from pathlib import Path

from polars import (Int32, Schema, String, UInt8, UInt16, DataType)
from NIHData.domain.types import NIHExporterHeader

BASE_NIH_SCHEMA: Schema[NIHExporterHeader, DataType] = Schema(
    {'APPLICATION_ID': String,
     'ACTIVITY': String,
     'ADMINISTERING_IC': String,
     'APPLICATION_TYPE': String,
     'ARRA_FUNDED': String,
     'AWARD_NOTICE_DATE': String,
     'BUDGET_START': String,
     'BUDGET_END': String,
     'ASSISTANCE_LISTING_NUMBER': String,
     'CORE_PROJECT_NUM': String,
     'ED_INST_TYPE': String,
     'OPPORTUNITY NUMBER': String,
     'FULL_PROJECT_NUM': String,
     'FUNDING_ICs': String,
     'FUNDING_MECHANISM': String,
     'FY': UInt16,
     'IC_NAME': String,
     'NIH_SPENDING_CATS': String,
     'ORG_CITY': String,
     'ORG_COUNTRY': String,
     'ORG_DEPT': String,
     'ORG_DISTRICT': String,
     'ORG_DUNS': String,
     'ORG_FIPS': String,
     'ORG_IPF_CODE': String,
     'ORG_NAME': String,
     'ORG_STATE': String,
     'ORG_ZIPCODE': String,
     'PHR': String,
     'PI_IDS': String,
     'PI_NAMEs': String,
     'PROGRAM_OFFICER_NAME': String,
     'PROJECT_START': String,
     'PROJECT_END': String,
     'PROJECT_TERMS': String,
     'PROJECT_TITLE': String,
     'SERIAL_NUMBER': String,
     'STUDY_SECTION': String,
     'STUDY_SECTION_NAME': String,
     'SUBPROJECT_ID': String,
     'SUFFIX': String,
     'SUPPORT_YEAR': UInt8,
     'DIRECT_COST_AMT': Int32,
     'INDIRECT_COST_AMT': Int32,
     'TOTAL_COST': Int32,
     'TOTAL_COST_SUB_PROJECT': Int32
     }
)


def _generate_variables(s: dict | Schema):
    directory = Path(__file__).parent / 'generated'
    directory.mkdir(exist_ok=True)
    init_py = (directory / "__init__.py")
    init_py.touch()
    generated_code_file = directory / "variables.py"

    lines = ['import polars as pl\n\n', ]

    lines.extend([f"{k.strip().replace(" ", "_")} = \'{k}\'\n" for k in s.keys()])
    lines.append('\n\n')
    lines.append("class NIHDataColumn:\n")
    lines.append("    \"\"\"Generated by _generate_variables() function from the schemas.py file\"\"\"\n")
    lines.extend([f"    {k.strip().replace(" ", "_")} = pl.col(\'{k}\')\n" for k in s.keys()])
    content = "".join(lines)

    generated_code_file.write_text(content, encoding='utf-8')

    file_content = generated_code_file.read_bytes()
    print(file_content)

    return generated_code_file


def _main():
    _generate_variables(BASE_NIH_SCHEMA)


if __name__ == '__main__':
    _main()
